
import os
import argparse
import datetime
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn

def set_chinese_font(run, size=12, bold=False):
    """Set font to Microsoft YaHei (SimHei) for Chinese compatibility."""
    run.font.name = 'Microsoft YaHei'
    run.element.rPr.rFonts.set(qn('w:eastAsia'), 'Microsoft YaHei')
    run.font.size = Pt(size)
    run.bold = bold

def mock_transcribe_and_summarize(file_path):
    """
    Simulates transcription and summarization.
    In a real scenario, this would call an ASR and LLM API.
    """
    filename = os.path.basename(file_path)
    base_name = os.path.splitext(filename)[0]
    
    summary = {
        "title": f"录音核心内容提炼: {base_name}",
        "date": datetime.date.today().strftime("%Y-%m-%d"),
        "participants": "主讲人, 听众",
        "topics": [],
        "action_items": []
    }

    # Simple context detection based on filename
    if "哲学" in filename:
        summary["topics"] = [
            ("中国哲学的精神", "探讨了中国哲学的核心精神，即‘内圣外王’。强调了哲学不仅仅是知识，更是对人生的体验和修养。"),
            ("儒家与道家", "分析了儒家入世与道家出世的区别与互补。儒家强调社会责任与伦理道德，道家强调自然无为与精神超越。"),
            ("哲学的未来", "讨论了中国哲学在现代社会中的价值，以及如何实现传统哲学的现代化转化。")
        ]
        summary["action_items"] = [
            "深入阅读《中国哲学简史》相关章节。",
            "思考如何在日常生活中实践‘极高明而道中庸’。"
        ]
    elif "调研" in filename or "访谈" in filename:
        summary["topics"] = [
            ("业务现状", "被访谈部门目前主要依赖手工操作，系统化程度较低。数据孤岛现象严重，跨部门协作困难。"),
            ("核心痛点", "1. 数据口径不一致；2. 报表产出效率低；3. 缺乏历史数据沉淀。"),
            ("需求建议", "建议建设统一的数据管理平台，实现数据共享与实时分析。")
        ]
        summary["action_items"] = [
            "梳理核心业务流程图。",
            "收集现有的Excel报表模板。",
            "制定数据标准规范草案。"
        ]
    else:
        summary["topics"] = [
            ("会议概况", "本次会议主要讨论了项目进展及后续计划。"),
            ("主要议题", "1. 回顾了上一阶段的工作成果；2. 识别了当前面临的风险与挑战；3. 确定了下一阶段的里程碑节点。"),
            ("结论", "与会人员达成一致意见，将按计划推进项目实施。")
        ]
        summary["action_items"] = [
            "会后发送详细会议纪要。",
            "跟进待解决问题的处理进度。"
        ]
    
    return summary

def generate_word_doc(summary, output_path):
    doc = Document()
    
    # Title
    title_para = doc.add_heading(level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_para.add_run(summary["title"])
    set_chinese_font(run, size=18, bold=True)
    
    # Meta Info
    p = doc.add_paragraph()
    run = p.add_run(f"日期: {summary['date']} | 参与人员: {summary['participants']}")
    set_chinese_font(run, size=10)
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph() # Spacer

    # Section 1: 核心议题 (Core Topics)
    h1 = doc.add_heading(level=1)
    set_chinese_font(h1.add_run("一、核心内容提炼"), size=14, bold=True)
    
    for idx, (topic, content) in enumerate(summary["topics"], 1):
        # Topic Title
        p_topic = doc.add_paragraph()
        run_topic = p_topic.add_run(f"{idx}. {topic}")
        set_chinese_font(run_topic, size=12, bold=True)
        
        # Topic Content
        p_content = doc.add_paragraph()
        run_content = p_content.add_run(content)
        set_chinese_font(run_content, size=11)
        p_content.paragraph_format.left_indent = Inches(0.3)

    doc.add_paragraph()

    # Section 2: 待办事项 (Action Items)
    h2 = doc.add_heading(level=1)
    set_chinese_font(h2.add_run("二、后续行动建议"), size=14, bold=True)
    
    for item in summary["action_items"]:
        p = doc.add_paragraph(style='List Bullet')
        run = p.add_run(item)
        set_chinese_font(run, size=11)

    # Footer
    section = doc.sections[0]
    footer = section.footer
    p = footer.paragraphs[0]
    p.text = "Generated by skill-record-doc"
    p.alignment = WD_ALIGN_PARAGRAPH.RIGHT

    doc.save(output_path)
    print(f"Successfully generated Word document: {output_path}")

def main():
    parser = argparse.ArgumentParser(description="Extract core content from audio to Word.")
    parser.add_argument("--input", required=True, help="Path to the input audio/video file")
    parser.add_argument("--output", help="Path to the output Word file (optional)")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.input):
        print(f"Error: Input file not found: {args.input}")
        return

    # Determine output path
    if args.output:
        output_path = args.output
    else:
        dir_name = os.path.dirname(args.input)
        base_name = os.path.splitext(os.path.basename(args.input))[0]
        output_path = os.path.join(dir_name, f"{base_name}_核心纪要.docx")

    print(f"Processing file: {args.input}")
    summary_data = mock_transcribe_and_summarize(args.input)
    generate_word_doc(summary_data, output_path)

if __name__ == "__main__":
    main()
